name: GitOps Deploy 1

on:
  workflow_dispatch:
  push:

concurrency:
  group: "deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Running deploy..."
          sleep 3
          echo "Done."
