name: Test Git Cloning

on:
  workflow_dispatch:
  push:

concurrency:
  group: "deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gatecheckdev/deploykit@main
