name: Test Git Cloning

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bacchusjackson/m
          ssh-key: ${{ secrets.MANIFEST_DEPLOY_TOKEN }}

      - uses: gatecheckdev/deploykit-action@experimental
        with:
          image: "some-experimental-image:abc123"
          service: "knight-light-server-flask"
          service-directory: "impl"
          manifest-deploy-token: ${{ secrets.MANIFEST_DEPLOY_TOKEN }}
