name: Image Delivery
run-name: "Build & Push Image"
on:
  workflow_dispatch:
  push:

jobs:
  image_delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: generate tag
      id: vars
      run: |
        image_repo=ttl.sh/$(cat /proc/sys/kernel/random/uuid)
        image_tag=30m
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          image_tag=${GITHUB_REF/refs\/tags\//}
        fi
        echo image_tags=$image_repo:$image_tag >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.vars.outputs.image_tags }}

